name: Publish workflow
run-name: Publish to NPM

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Get PR labels
        id: get_labels
        run: echo "PR_LABELS=$(jq -r '.pull_request.labels | map(.name) | join(",")' <<< '${{ toJson(github.event) }}')" >> $GITHUB_ENV
      - name: increase_version
        id: increase_version
        run: |
          if [[ "${{ env.PR_LABELS }}" == *"major"* ]]; then
            npm version major --no-git-tag-version
          elif [[ "${{ env.PR_LABELS }}" == *"minor"* ]]; then
            npm version minor --no-git-tag-version
          elif [[ "${{ env.PR_LABELS }}" == *"patch"* ]]; then
            npm version patch --no-git-tag-version
          else
            echo "Error: No version tag (major, minor, patch) found in PR labels"
            exit 1
          fi
      - name: Publish
        run: |
          sleep 5;
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
