name: Publish workflow
run-name: Publish to NPM
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Get PR labels
        id: pr
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          PR_LABELS=$(gh pr view https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} --json labels -q ".labels[].name")
          echo "PR_LABELS=$PR_LABELS" >> $GITHUB_ENV
      - name: Increase version
        run: |
          if [[ "${{ env.PR_LABELS }}" == *"major"* ]]; then
            npm version major
          elif [[ "${{ env.PR_LABELS }}" == *"minor"* ]]; then
            npm version minor
          elif [[ "${{ env.PR_LABELS }}" == *"patch"* ]]; then
            npm version patch
          fi
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
