name: Publish workflow
run-name: Publish to NPM

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build
        run: npm run build

  version:
    runs-on: ubuntu-latest
    steps:
      - name: increase_version
        id: increase_version
        run: |
          if [[ "${{ github.event.pull_request.labels.name }}" == *"major"* ]]; then
            npm version major --no-git-tag-version
          elif [[ "${{ github.event.pull_request.labels.name }}" == *"minor"* ]]; then
            npm version minor --no-git-tag-version
          elif [[ "${{ github.event.pull_request.labels.name }}" == *"patch"* ]]; then
            npm version patch --no-git-tag-version
          fi

  publish:
    runs-on: ubuntu-latest
    needs: [build, version]
    steps:
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
