name: Publish workflow
run-name: Publish to NPM
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Get PR labels
        id: get_labels
        run: echo "PR_LABELS=$(jq -r '.pull_request.labels | map(.name) | join(",")' <<< '${{ toJson(github.event) }}')" >> $GITHUB_ENV
        shell: bash
      - name: Increase version
        id: increase_version
        run: |
          if [[ "${{ env.PR_LABELS }}" == *"major"* ]]; then
            npm version major --no-git-tag-version
          elif [[ "${{ env.PR_LABELS }}" == *"minor"* ]]; then
            npm version minor --no-git-tag-version
          elif [[ "${{ env.PR_LABELS }}" == *"patch"* ]]; then
            npm version patch --no-git-tag-version
          else
            echo "Error: No version tag (major, minor, patch) found in PR labels"
            exit 1
      - name: Wait before publishing
        run: sleep 30
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
